on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ./**.yaml
      - ./**.yml
name: Cluster Capacity Check
jobs:
  check_capacity:
    runs-on: ubuntu-latest
    name: Check capacity 
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v29
        with:
          files: |
            *.yml
            *.yaml

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_modified_files }}; do
            echo "$file was modified"
          done

      - name: Read new requested resources from YAML.
        id: yaml-data
        uses: jbutcher5/read-yaml@1.6
        with:
          file: ${{ steps.changed-files-specific.outputs.all_modified_files }}  # File to read from
          key-path: '["spec", "containers", "resources", "limits", "cpu"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
        
    
    
#spec.source.helm.values.resources.limits.cpu
#spec.source.helm.values.resources.limits.memory
#spec.source.helm.values.resources.requests.cpu
#spec.source.helm.values.resources.requests.memory
    